#! /usr/bin/env python
import json
import datetime
import requests
import sys

def update():
    cap = raw_input("Current cap: ")
    time = datetime.datetime.today().strftime("%I:%M%p %B %d %Y")
    js = json.dumps({"data": cap, "time": time})
    rs = requests.post("http://raspberrypi/update",data=js)
    print "Response: ", rs.text

if __name__ == "__main__":
    update()
